### PR TITLE
Fix two memory leaks, various warnings, and other tweaks

### PR DESCRIPTION
**Pull request by fingolfin**
The memory leaks were found using https://clang-analyzer.llvm.org

### CODE REVIEW

**Comment by DominikBernhardt** [comment]
Also, do you want to update this PR so we can merge it without a failed check?

**Comment by DominikBernhardt** [comment]
@fingolfin codevov/patch is still not happy, but I think we could merge this?

**Comment by fingolfin** [comment]
Yes, please merge. I don't understand why `.codecov.yml` has no effect.

**Comment by DominikBernhardt** [comment]
`.codecov.yml` is again contained in #84 . Maybe merging that helps..

**Pull request merged**
