### PR TITLE
Testfiles from manual examples

### PR DESCRIPTION
**Pull request by gaehler**
This PR converts the manual examples to testfiles. This should increase the code coverage and add some confidence that nothing goes wrong when non-trivial changes to the code are made. Also included are some bugfixes required for the tests to succeed, and corrections to some manual examples. The latter should not be forgotten when converting the web pages to gh-pages.

### CODE REVIEW

**Comment by gaehler** [comment]
The CI test on Windows are a bit of a mixed blessing. They seem to fail often even if they run through on Linux. I hope that such tests which fail on some (unsupported) systems do not prevent a PR from being merged. After all, it's not the test which is faulty, and a test which fails on some systems is still better than no test at all. I have disabled `Ex13.tst` for the moment, only to see that now `Ex1.tst` fails. I'm not willing to disable many of them.

**Comment by alex-konovalov** [comment]
Yes, I am curious to know what's the reason behind e.g. diffs at https://ci.appveyor.com/project/alex-konovalov/carat/builds/21017174/job/adgo6rv953wdc640 and do they point to a serious problems. 

It is up to us to establish minimal standards for merging PRs, and in this stage it seems reasonable to me to allow tests on Windows to fail.

**Comment by gaehler** [comment]
On Windows, there is quite some difference between 32bit and 64bit. I'm not sure whether this has been tested on Linux, or whether we just made sure that it builds.
I encountered several instances of uninitialized variables. Surely, there will be more, and these may lead to surprising differences between different systems.

**Comment by DominikBernhardt** [comment]
I also think that at this point we should merge such commits even though some test on Windows fail, depending on the impact of the commit of course. Any objections?

**Comment by alex-konovalov** [comment]
Not bad to have 59% code coverage - thanks for the tests @gaehler!

**Pull request merged**
