### PR TITLE
Remove dead code (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by fingolfin**
This removes a lot of code which was either never compiled; or at least never invoked.

This is an alternative to PR #66 ; closes #66

Whether we want this or not is up to debate; I merely put this here for discussion, and it should certainly not be merged lightly.

### CODE REVIEW

**Comment by DominikBernhardt** [comment]
This would indeed be a lot of code to delete. I get more and more hesitant when thinking about it. I might speak to Prof. Plesken once I'm back in Aachen. He probably doesn't know what this code was intended for, but he might know if there is someone we could contact?
So right now, I would opt for the alternative to this PR #66  and just label the code as unused.

**Comment by gaehler** [comment]
CARAT apparently contains quite a few parts which were experimental, not finished, not documented, or not made official for some other reason. Also, CARAT contains collections of utilities from earlier projects, not all of which are actually used in CARAT. For an outsider, it's hard to tell what the intent of these developments were, and in what state they are, and how they would be used. I really do not see how an outsider would be able to pick up and finish such developments, given the scarce documentation available. On the other hand, I'm also hesitant to through away that much code, especially as it's not my code, not even that of my institution. Marking such code as currently unused is perhaps a good compromise.

**Comment by DominikBernhardt** [comment]
I agree with @gaehler there. The code is from my University, but was written when I was still in school... As there is a lot of dead code, should we maybe make a directory that contains all this code @fingolfin ? That would result in the other folders only containing code that is actually used. It is not ideal, but I feel uneasy deleting that much code..

**Comment by fingolfin** [comment]
I am fine in just leaving this code in. Marking it as "unused" did the job for me just fine -- it just helps me know which code I need to worry about and which I can ignore.

There are indeed lots of other tools in there which are never executed by the test suite, e.g. for adding matrices in input files. I don't think these are that useful these days, but perhaps somebody still has use for them? I think it would be good to either add tests for them, or else also disable them... but that's not something I want to explore right now.

**Pull request closed without merging**
