### PR TITLE
Add xmalloc and xrealloc helpers

### PR DESCRIPTION
**Pull request by fingolfin**
This is mostly about making the code easier to read, by hiding error checking away.

DO NOT MERGE before PR <s>#77</s> #82 was merged; at that point, I'll have to regenerate this PR. But since it was partially generated by a script, that will be easier than doing it the other way around.

### CODE REVIEW

**Comment by fingolfin** [comment]
@DominikBernhardt I'll rebase this once PR #82 is merged, as that will cause multiple additional conflicts.

**Comment by DominikBernhardt** [comment]
@fingolfin Merged #82

**Comment by fingolfin** [comment]
@DominikBernhardt updated

**Comment by DominikBernhardt** [comment]
@fingolfin This still has conflicts.

**Comment by fingolfin** [comment]
Resolved conflicts (for the 4th time ;-)

**Comment by DominikBernhardt** [comment]
I'll merge this once the tests habe passed. :-) Thanks!

**Comment by fingolfin** [comment]
@DominikBernhardt the AppVeyor test failed, but only because of a network issue uploading the coverage report. But I don't have the permissions on AppVeyor to restart that job. Either you do it, or just merge this as is, as I am sure that was just a temporary fluke.

**Comment by DominikBernhardt** [comment]
@fingolfin I'll merge this now as all checks have passed. Thanks!

**Pull request merged**
