### PR TITLE
Reduce compiler warnings and improve testing

### PR DESCRIPTION
**Pull request by gaehler**
This PR eliminates most of the compiler warnings (those with obvious fixes). Remaining are an interface mismatch with `all_cocycles` (this is a bit scary) and pointer size mismatches in `functions/M_alloc/m_alloc.c` (we need an integer of the same size as a pointer - should be determined at configure time).

I also changed testing, so that it does not stop on the first task with non-zero exit code (and without displaying any diagnostic messages). Rather, all output up to this point is displayed, along with any diagnostic messages and the exit code of the failed task. After that, testing continues with the next task.

### CODE REVIEW

**Comment by gaehler** [comment]
The variable CC is not properly propagated, and so we are testing twice with gcc. Is there a reason that you work with sed on the Makefile, rather than just doing something like

```make TOPDIR="some path" CFLAGS="some flags" CC="$(CC)"```

By the way: my comment on having eliminated "most" compiler warnings referred to a setting without the flag `-Wall`.

**Comment by gaehler** [comment]
Regarding tests on Windows, 32bit doesn't look too bad. There are two segfaults in Graph and Order, but all the rest runs fine. 64bit looks much worse, though. One problem might be the diagnostic wrapper around `malloc` and friends in `functions/M_alloc/`, which is not 64bit clean. This problem could be circumvented by avoiding compilation with `-DDIAG1` or `-DDIAG2`.

**Comment by DominikBernhardt** [comment]
@alex-konovalov Wrote the sed-code, so maybe he can comment on this?

I think this can be merged once Alex' says something about the sed part, as we said that we might ignore failing windows tests for now.

**Comment by alex-konovalov** [comment]
Closed via a2ceae700d156fd8e8a8a99af5d48155329112c6, 773373c03acd01f5224c0b935eb4728655e198a6 and ceb53cbfee23ec53cb61cdb4440622ce142b4b7e (I had to rebase it to remove merge commit).

We use `bash -e` in GAP to stop after the first error, but there tests take much more time, so it's desirable so. Also, sometimes failures are cascading. But for Carat, for now at least, we can afford running all tests, and it may be interesting to see the full picture of failures if they occur.

**Pull request closed without merging**
