### PR TITLE
Uninitialized variable leads to silly numbering of Z-classes

### PR DESCRIPTION
**Pull request by gaehler**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@gaehler BTW, there are now tests in https://github.com/lbfm-rwth/carat/tree/master/tst - see e.g. https://github.com/lbfm-rwth/carat/blob/master/tst/Bravais.tst which has some instructions in comments. So you can now provide test files to demonstrate that the fix works.

**Comment by alex-konovalov** [comment]
@gaehler thanks for adding tests! It failed though - observed output says `0-th homogenously` while `1-th homogenously` is expected:

```
< #g1 f3 n4 % 0-th homogenously dec. group, 1 zclass
---
> #g1 f3 n4 % 1-th homogenously dec. group, 1 zclass
QtoZ.tst failed, see observed/expected output above
```

**Comment by gaehler** [comment]
It seems my test file has uncovered another, more subtle bug. The numbering of homogeneously decomposable groups seems to depend on the machine/compiler/os combination (starting either with 0 or with 1). I do not understand the algorithm well enough to know what the intended numbering is, and how the difference comes about.

**Comment by gaehler** [comment]
The test `if (is_option('a') || Classes[i + no])` in file `src/qtoz.c` is not reliable. There are cases where Classes has only length `no`, and `Classes[i+no] `is thus not defined (see the beginning of function `q2z` in `functions/ZZ/q2z.c`). Anything can happen then. Not sure how to solve this.

**Comment by gaehler** [comment]
Problematic was only a short-cut for a trivial case, which I could fix.

**Pull request merged**
